version: "2"
linters:
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        source: defer
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/azizuysal/simtool
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
