# This config is for golangci-lint
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      source: "defer"
    - path: _test\.go
      linters:
        - errcheck

run:
  timeout: 5m